### ISSUE TITLE
cocos2d-x 3.9 iOS integration failed

### ISSUE THREAD

**Issue by xiongdi9456** [shephertz/AppWarpCocos2DX#7]
Hi,I did follow the tutorial,add curl from external.then build.

Errors like this:

`Undefined symbols for architecture x86_64:
  "_curl_easy_cleanup", referenced from:
      AppWarp::Client::lookup() in appwarp.o
  "_curl_easy_getinfo", referenced from:
      AppWarp::Client::lookup() in appwarp.o
  "_curl_easy_init", referenced from:
      AppWarp::Client::lookup() in appwarp.o
  "_curl_easy_perform", referenced from:
      AppWarp::Client::lookup() in appwarp.o
  "_curl_easy_setopt", referenced from:
      AppWarp::Client::lookup() in appwarp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by RajeevRShephertz** [comment]
It seems this issue is coming on iOS Simulator. It is running fine on iPhone device. 
It is due to the curl lib in cocos2dx bundle. It seems, it is not built to support x86_64 architecture.

**Comment by chenxufeiyue** [comment]
Should manually add **libcurl.a** file from _**cocos2d/external/curl/prebuild**_ to _**Link Binary with Libraries**_ in Build Phases

**Comment by mdbanares** [comment]
I also have the same issue even if I try to run it on iPhone device.

**Comment by angyay0** [comment]
@mdbanares  so do i. I try to compile it for an ios 9.3.3 iPhone 5s and got that problem. @RachitSShephertz Could you help ups?

**Comment by angyay0** [comment]
You could try doing this:
Header Search Path > add curl/include/ios
Library Search Path > add curl/prebuilt/ios

then add a linker flag to your target 
Other Linker Flags >  add -lcurl

That solve the problem for me, in both architectures. 
Hope it works!!
